apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: easycrm-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgC4pK/3DbUnivK6GbsgBUVQPO3UairtctAfc2wetncqnXXTa/e8sSQvj70XZsalB9O5RsWnHKxqkYfWBM1KtxEb1rUertPkmUP0WX28iDgge2a1xWyTfcxJWLQ5SaPbWj5df1mBcjDSInjuree/8E3H7arTGLUr3mO3n03gYoB8x+Vlat65cUqXgdG/dTzX9lBO4ZI+P23RjQ5L15Bs/8FxZPVQHK3AW2ynrbeqgTTRcXm7zoHjkKrzaUN4lrmI5ZoE4Ni7Li6+CjqtDlN4cffmxfmIJLwJ1cQKI9+Tb7tKravmeKJiNlFkAHcUQ6ggnNedAMdzawRtxRwY/H1bt3Hfj4x+Fum5+MRnSmFOFxGcYb8Qks1eXS1dUluPsuyIvXzkTWrTEb5+7TcWA3lh3rQ2JZiBg6e/YQWb+aafA+qQMObuCBGGbm1lWY7+ZwnX/NaeiCWJbTRtBTql4Njfm8C3fGUjzq7Xt45xE/8a+3n2ZFuLR57PXydzjE4KWwxVE5fxRxm9RZbP9r5Xe7sP5OR6zTNAma9sLm1trDQAEiUU0kLL2DiXxbJsUtazlxCwgq6drRAORzJGVitXTBVw4A1ZMQ7mY9Y/k1WgcYf+pdjmqi9SPi2g2mskmvw5rG4TFrtKW4m9XVK8Rgdbxfy/97NCBxryGXkG7BOSm/60JWhm+9P+Q5bT8uYlR3/Gyg7dtW0UP7wEB9DKXTDR84DU+SLA5f0=
  template:
    metadata:
      creationTimestamp: null
      name: easycrm-db-secret
      namespace: default
