---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: easycrm-db-secret
  namespace: default
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgAnqf9Z4SK60LfZtD+YUUfrWDiHm9J7oUY7mSzVSmS/Ze/OREvhWt/TbHeuq4G18n8hDt3N7th5cNL7lq7VxgEWDNq9foq01g4GdbDAt+J0+XSiebS8qrok9xvz2/bjcYjB78hTr+7HcIyYE9ZlBF1KRoF0TDSoU7OtKLVhONJ43L/++OGrcXd+33+IWXg/VWrygGTnHV1gEbx7Y1ZEd/3you9WfXD1JUFJBKB21vWeY4irx6f50BYX4H+bFd4tLTWq1RqOCvw3Wh2s6x9CJsLyz19jWT5ta9ayU5/8aHvSUGJG7tKx14lXI5SBpmidsjNccB3feB0GXPGTinykqP3RRWUlLMhILfq8nay2tkzsU9FCEX/bcDNdj3gqEL1p5Ax/IbUiP1fM8yAoW8MxKHIUSdpEz4MQAx934WIdaSjP81iZEACHrU07pO6zrkn7yF+jpLIFHqbEC3mb7dGklj3N+MLsN6PPeTVOPhk6cIaqw6dAXo2uYcR6+pg7rzcE10H0e0pO5UnEabUIu+/XmV2PcRfX1o7cpCxGIjOVjel+e7AL2DXNKUE+eXQy69iO59lhU48CJCpPMw73uynVUBGWZPBA6s848qvIxj+X7qQMq947xtfWkaItVPJ6HkUfvu+TXOrC6yyb2qZEODMh2Aq3TjyNui7q2zMJzzcCqqzCndbKYDd9Z6K0H5a5BhXRQvrOQFY8TRx3b1BRG3XKLeNu90YmTLyh0rw=
  template:
    metadata:
      creationTimestamp: null
      name: easycrm-db-secret
      namespace: default
    type: Opaque
